import { slugify } from "@/lib/utils";
import type { ExerciseType, MuscleGroup } from "./types";

type Row = {
  name: string;
  muscle: MuscleGroup;
  type: ExerciseType;
  equipment: string;
  id?: string;
};

const RAW: Row[] = [
  // Pecho
  { id: "bench_press", name: "Press de banca", muscle: "Pecho", type: "Compuesto", equipment: "Barra" },
  { name: "Press de banca inclinado", muscle: "Pecho", type: "Compuesto", equipment: "Barra" },
  { name: "Press de banca declinado", muscle: "Pecho", type: "Compuesto", equipment: "Barra" },
  { id: "db_bench", name: "Press con mancuernas", muscle: "Pecho", type: "Compuesto", equipment: "Mancuernas" },
  { id: "incline_db_press", name: "Press inclinado con mancuernas", muscle: "Pecho", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Press declinado con mancuernas", muscle: "Pecho", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Aperturas con mancuernas", muscle: "Pecho", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Aperturas inclinadas", muscle: "Pecho", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Cruces en polea", muscle: "Pecho", type: "Aislamiento", equipment: "Cable" },
  { name: "Cruces en polea alta", muscle: "Pecho", type: "Aislamiento", equipment: "Cable" },
  { name: "Cruces en polea baja", muscle: "Pecho", type: "Aislamiento", equipment: "Cable" },
  { name: "Fondos en paralelas", muscle: "Pecho", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Press en máquina", muscle: "Pecho", type: "Compuesto", equipment: "Máquina" },
  { name: "Peck deck", muscle: "Pecho", type: "Aislamiento", equipment: "Máquina" },
  { name: "Press en Smith", muscle: "Pecho", type: "Compuesto", equipment: "Smith" },
  { name: "Flexiones", muscle: "Pecho", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Flexiones inclinadas", muscle: "Pecho", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Flexiones declinadas", muscle: "Pecho", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Flexiones con palmas elevadas", muscle: "Pecho", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Pullover con mancuerna", muscle: "Pecho", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Floor press", muscle: "Pecho", type: "Compuesto", equipment: "Barra" },
  { name: "Press Svend", muscle: "Pecho", type: "Aislamiento", equipment: "Disco" },
  { name: "Press inclinado en Smith", muscle: "Pecho", type: "Compuesto", equipment: "Smith" },
  { name: "Press en máquina Hammer", muscle: "Pecho", type: "Compuesto", equipment: "Máquina" },
  { name: "Aperturas en cable unilateral", muscle: "Pecho", type: "Aislamiento", equipment: "Cable" },
  // Espalda
  { id: "deadlift", name: "Peso muerto", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { id: "rdl", name: "Peso muerto rumano", muscle: "Femorales", type: "Compuesto", equipment: "Barra" },
  { name: "Peso muerto sumo", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Peso muerto deficit", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { id: "pullup", name: "Dominadas", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Dominadas supinas", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Dominadas neutras", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Dominadas asistidas", muscle: "Espalda", type: "Compuesto", equipment: "Máquina" },
  { id: "lat_pulldown", name: "Jalón al pecho", muscle: "Espalda", type: "Compuesto", equipment: "Cable" },
  { name: "Jalón agarre cerrado", muscle: "Espalda", type: "Compuesto", equipment: "Cable" },
  { name: "Jalón agarre amplio", muscle: "Espalda", type: "Compuesto", equipment: "Cable" },
  { id: "barbell_row", name: "Remo con barra", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Remo Pendlay", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Remo con mancuerna", muscle: "Espalda", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Remo en T", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Remo en polea baja", muscle: "Espalda", type: "Compuesto", equipment: "Cable" },
  { name: "Remo sentado", muscle: "Espalda", type: "Compuesto", equipment: "Cable" },
  { name: "Remo en máquina", muscle: "Espalda", type: "Compuesto", equipment: "Máquina" },
  { id: "face_pull", name: "Face pull", muscle: "Espalda", type: "Aislamiento", equipment: "Cable" },
  { name: "Hiperextensiones", muscle: "Espalda", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Remo invertido", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Encogimientos con barra", muscle: "Espalda", type: "Aislamiento", equipment: "Barra" },
  { name: "Encogimientos con mancuernas", muscle: "Espalda", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Straight arm pulldown", muscle: "Espalda", type: "Aislamiento", equipment: "Cable" },
  { name: "Meadows row", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Seal row", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Good morning", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Remo unilateral en cable", muscle: "Espalda", type: "Compuesto", equipment: "Cable" },
  { name: "Jalón un brazo", muscle: "Espalda", type: "Compuesto", equipment: "Cable" },
  { name: "Remo en Smith", muscle: "Espalda", type: "Compuesto", equipment: "Smith" },
  // Hombros
  { id: "ohp", name: "Press militar", muscle: "Hombros", type: "Compuesto", equipment: "Barra" },
  { name: "Press militar con mancuernas", muscle: "Hombros", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Press Arnold", muscle: "Hombros", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Press sentado en máquina", muscle: "Hombros", type: "Compuesto", equipment: "Máquina" },
  { name: "Press en Smith militar", muscle: "Hombros", type: "Compuesto", equipment: "Smith" },
  { id: "lateral_raise", name: "Elevaciones laterales", muscle: "Hombros", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Elevaciones laterales en cable", muscle: "Hombros", type: "Aislamiento", equipment: "Cable" },
  { name: "Elevaciones laterales en máquina", muscle: "Hombros", type: "Aislamiento", equipment: "Máquina" },
  { name: "Elevaciones frontales", muscle: "Hombros", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Pájaros", muscle: "Hombros", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Pájaros en pec deck", muscle: "Hombros", type: "Aislamiento", equipment: "Máquina" },
  { name: "Remo al mentón", muscle: "Hombros", type: "Compuesto", equipment: "Barra" },
  { name: "Press de hombro unilateral", muscle: "Hombros", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Face pull a 90°", muscle: "Hombros", type: "Aislamiento", equipment: "Cable" },
  { name: "Elevación lateral tumbado", muscle: "Hombros", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Press landmine", muscle: "Hombros", type: "Compuesto", equipment: "Barra" },
  { name: "Y-raise", muscle: "Hombros", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Cuban press", muscle: "Hombros", type: "Compuesto", equipment: "Mancuernas" },
  // Bíceps
  { id: "barbell_curl", name: "Curl con barra", muscle: "Bíceps", type: "Aislamiento", equipment: "Barra" },
  { name: "Curl con barra Z", muscle: "Bíceps", type: "Aislamiento", equipment: "Barra" },
  { id: "hammer_curl", name: "Curl martillo", muscle: "Bíceps", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Curl con mancuernas", muscle: "Bíceps", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Curl predicador", muscle: "Bíceps", type: "Aislamiento", equipment: "Barra" },
  { name: "Curl concentrado", muscle: "Bíceps", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Curl en cable", muscle: "Bíceps", type: "Aislamiento", equipment: "Cable" },
  { name: "Curl bayesian", muscle: "Bíceps", type: "Aislamiento", equipment: "Cable" },
  { name: "Curl 21s", muscle: "Bíceps", type: "Aislamiento", equipment: "Barra" },
  { name: "Curl inclinado", muscle: "Bíceps", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Curl spider", muscle: "Bíceps", type: "Aislamiento", equipment: "Barra" },
  { name: "Curl en máquina", muscle: "Bíceps", type: "Aislamiento", equipment: "Máquina" },
  { name: "Curl martillo en cable", muscle: "Bíceps", type: "Aislamiento", equipment: "Cable" },
  { name: "Drag curl", muscle: "Bíceps", type: "Aislamiento", equipment: "Barra" },
  // Tríceps
  { id: "pushdown", name: "Extensión en polea", muscle: "Tríceps", type: "Aislamiento", equipment: "Cable" },
  { name: "Extensión en polea cuerda", muscle: "Tríceps", type: "Aislamiento", equipment: "Cable" },
  { id: "oh_extension", name: "Extensión por encima de la cabeza", muscle: "Tríceps", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Press francés", muscle: "Tríceps", type: "Aislamiento", equipment: "Barra" },
  { name: "Fondos en banco", muscle: "Tríceps", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Patada de tríceps", muscle: "Tríceps", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Press cerrado", muscle: "Tríceps", type: "Compuesto", equipment: "Barra" },
  { name: "Extensión en máquina", muscle: "Tríceps", type: "Aislamiento", equipment: "Máquina" },
  { name: "Extensión unilateral en cable", muscle: "Tríceps", type: "Aislamiento", equipment: "Cable" },
  { name: "Tate press", muscle: "Tríceps", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "JM press", muscle: "Tríceps", type: "Compuesto", equipment: "Barra" },
  { name: "Flexiones diamante", muscle: "Tríceps", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Extensión en polea inversa", muscle: "Tríceps", type: "Aislamiento", equipment: "Cable" },
  { name: "Press cerrado en Smith", muscle: "Tríceps", type: "Compuesto", equipment: "Smith" },
  // Cuádriceps
  { id: "squat", name: "Sentadilla", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Sentadilla frontal", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Sentadilla goblet", muscle: "Cuádriceps", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Sentadilla búlgara", muscle: "Cuádriceps", type: "Compuesto", equipment: "Mancuernas" },
  { id: "leg_press", name: "Prensa de piernas", muscle: "Cuádriceps", type: "Compuesto", equipment: "Máquina" },
  { name: "Extensión de cuádriceps", muscle: "Cuádriceps", type: "Aislamiento", equipment: "Máquina" },
  { name: "Zancadas", muscle: "Cuádriceps", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Zancadas caminando", muscle: "Cuádriceps", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Sentadilla hack", muscle: "Cuádriceps", type: "Compuesto", equipment: "Máquina" },
  { name: "Sentadilla en Smith", muscle: "Cuádriceps", type: "Compuesto", equipment: "Smith" },
  { name: "Sentadilla sissy", muscle: "Cuádriceps", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Step-up", muscle: "Cuádriceps", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Pendulum squat", muscle: "Cuádriceps", type: "Compuesto", equipment: "Máquina" },
  { name: "Sentadilla con pausa", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Sentadilla bóxer", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Prensa unilateral", muscle: "Cuádriceps", type: "Compuesto", equipment: "Máquina" },
  { name: "Heels-elevated squat", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Cyclist squat", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  // Femorales
  { name: "Curl femoral tumbado", muscle: "Femorales", type: "Aislamiento", equipment: "Máquina" },
  { name: "Curl femoral sentado", muscle: "Femorales", type: "Aislamiento", equipment: "Máquina" },
  { name: "Curl femoral de pie", muscle: "Femorales", type: "Aislamiento", equipment: "Máquina" },
  { name: "Peso muerto rumano con mancuernas", muscle: "Femorales", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Nordic curl", muscle: "Femorales", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Glute ham raise", muscle: "Femorales", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Peso muerto con piernas rígidas", muscle: "Femorales", type: "Compuesto", equipment: "Barra" },
  { name: "Sliding leg curl", muscle: "Femorales", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "RDL unipodal", muscle: "Femorales", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Good morning sentado", muscle: "Femorales", type: "Aislamiento", equipment: "Barra" },
  { name: "Curl femoral en cable", muscle: "Femorales", type: "Aislamiento", equipment: "Cable" },
  // Glúteos
  { id: "hip_thrust", name: "Hip thrust", muscle: "Glúteos", type: "Compuesto", equipment: "Barra" },
  { name: "Puente de glúteo", muscle: "Glúteos", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Patada de glúteo en cable", muscle: "Glúteos", type: "Aislamiento", equipment: "Cable" },
  { name: "Patada de glúteo en máquina", muscle: "Glúteos", type: "Aislamiento", equipment: "Máquina" },
  { name: "Abducción de cadera", muscle: "Glúteos", type: "Aislamiento", equipment: "Máquina" },
  { name: "Abducción con banda", muscle: "Glúteos", type: "Aislamiento", equipment: "Banda" },
  { name: "Hip thrust con mancuerna", muscle: "Glúteos", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Frog pump", muscle: "Glúteos", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Step-up lateral", muscle: "Glúteos", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Zancada inversa", muscle: "Glúteos", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Cable pull-through", muscle: "Glúteos", type: "Compuesto", equipment: "Cable" },
  { name: "Hip thrust unipodal", muscle: "Glúteos", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Clamshell", muscle: "Glúteos", type: "Aislamiento", equipment: "Banda" },
  // Pantorrillas
  { id: "calf_raise", name: "Elevación de gemelos de pie", muscle: "Pantorrillas", type: "Aislamiento", equipment: "Máquina" },
  { name: "Elevación de gemelos sentado", muscle: "Pantorrillas", type: "Aislamiento", equipment: "Máquina" },
  { name: "Elevación de gemelos en prensa", muscle: "Pantorrillas", type: "Aislamiento", equipment: "Máquina" },
  { name: "Elevación de gemelos con mancuerna", muscle: "Pantorrillas", type: "Aislamiento", equipment: "Mancuernas" },
  { name: "Donkey calf raise", muscle: "Pantorrillas", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Elevación unipodal de gemelos", muscle: "Pantorrillas", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Tibialis raise", muscle: "Pantorrillas", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Saltos a la comba", muscle: "Pantorrillas", type: "Cardio", equipment: "Peso corporal" },
  // Abdomen / Core
  { id: "plank", name: "Plancha", muscle: "Core", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Plancha lateral", muscle: "Core", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Crunch", muscle: "Abdomen", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Crunch en máquina", muscle: "Abdomen", type: "Aislamiento", equipment: "Máquina" },
  { name: "Crunch en cable", muscle: "Abdomen", type: "Aislamiento", equipment: "Cable" },
  { name: "Elevación de piernas colgado", muscle: "Abdomen", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Elevación de rodillas", muscle: "Abdomen", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Ab wheel", muscle: "Core", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Dead bug", muscle: "Core", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Bird dog", muscle: "Core", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Pallof press", muscle: "Core", type: "Aislamiento", equipment: "Cable" },
  { name: "Russian twist", muscle: "Abdomen", type: "Aislamiento", equipment: "Disco" },
  { name: "Mountain climbers", muscle: "Core", type: "Cardio", equipment: "Peso corporal" },
  { name: "Hollow body hold", muscle: "Core", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Dragon flag", muscle: "Abdomen", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Sit-up", muscle: "Abdomen", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "V-up", muscle: "Abdomen", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Woodchop", muscle: "Core", type: "Aislamiento", equipment: "Cable" },
  { name: "Farmer carry", muscle: "Core", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Suitcase carry", muscle: "Core", type: "Compuesto", equipment: "Mancuernas" },
  { name: "Toes to bar", muscle: "Abdomen", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Plancha con peso", muscle: "Core", type: "Aislamiento", equipment: "Disco" },
  // Cardio extra
  { name: "Carrera en cinta", muscle: "Core", type: "Cardio", equipment: "Máquina" },
  { name: "Elíptica", muscle: "Core", type: "Cardio", equipment: "Máquina" },
  { name: "Bicicleta estática", muscle: "Cuádriceps", type: "Cardio", equipment: "Máquina" },
  { name: "Remoergómetro", muscle: "Espalda", type: "Cardio", equipment: "Máquina" },
  { name: "Assault bike", muscle: "Core", type: "Cardio", equipment: "Máquina" },
  { name: "Sled push", muscle: "Cuádriceps", type: "Cardio", equipment: "Máquina" },
  { name: "Battle ropes", muscle: "Hombros", type: "Cardio", equipment: "Cuerda" },
  { name: "Burpees", muscle: "Core", type: "Cardio", equipment: "Peso corporal" },
  { name: "Jumping jacks", muscle: "Core", type: "Cardio", equipment: "Peso corporal" },
  { name: "Box jumps", muscle: "Cuádriceps", type: "Cardio", equipment: "Peso corporal" },
  { name: "Kettlebell swing", muscle: "Glúteos", type: "Compuesto", equipment: "Kettlebell" },
  { name: "Goblet squat con kettlebell", muscle: "Cuádriceps", type: "Compuesto", equipment: "Kettlebell" },
  { name: "Turkish get-up", muscle: "Core", type: "Compuesto", equipment: "Kettlebell" },
  { name: "Snatch con kettlebell", muscle: "Hombros", type: "Compuesto", equipment: "Kettlebell" },
  { name: "Clean and press", muscle: "Hombros", type: "Compuesto", equipment: "Barra" },
  { name: "Power clean", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Push press", muscle: "Hombros", type: "Compuesto", equipment: "Barra" },
  { name: "Thruster", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Wall ball", muscle: "Cuádriceps", type: "Compuesto", equipment: "Disco" },
  // Estiramientos
  { name: "Estiramiento de pectoral", muscle: "Pecho", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Estiramiento de dorsal", muscle: "Espalda", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Estiramiento de hombro", muscle: "Hombros", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Estiramiento de cuádriceps", muscle: "Cuádriceps", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Estiramiento de isquios", muscle: "Femorales", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Estiramiento de glúteo", muscle: "Glúteos", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Estiramiento de gemelo", muscle: "Pantorrillas", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Estiramiento de cadera 90/90", muscle: "Glúteos", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Gato-vaca", muscle: "Core", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Cobra", muscle: "Abdomen", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Pigeon pose", muscle: "Glúteos", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "World's greatest stretch", muscle: "Core", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Mobilidad de tobillo", muscle: "Pantorrillas", type: "Estiramiento", equipment: "Peso corporal" },
  { name: "Dislocaciones de hombro", muscle: "Hombros", type: "Estiramiento", equipment: "Banda" },
  { name: "Dead hang", muscle: "Espalda", type: "Estiramiento", equipment: "Peso corporal" },
  // Extra compounds / machines to pass 200
  { name: "Hack squat inverso", muscle: "Glúteos", type: "Compuesto", equipment: "Máquina" },
  { name: "Prensa horizontal", muscle: "Cuádriceps", type: "Compuesto", equipment: "Máquina" },
  { name: "Remo Hammer Strength", muscle: "Espalda", type: "Compuesto", equipment: "Máquina" },
  { name: "Jalón Hammer Strength", muscle: "Espalda", type: "Compuesto", equipment: "Máquina" },
  { name: "Press de pecho Hammer", muscle: "Pecho", type: "Compuesto", equipment: "Máquina" },
  { name: "Pec deck inverso", muscle: "Hombros", type: "Aislamiento", equipment: "Máquina" },
  { name: "Curl predicador en máquina", muscle: "Bíceps", type: "Aislamiento", equipment: "Máquina" },
  { name: "Fondos en máquina", muscle: "Tríceps", type: "Compuesto", equipment: "Máquina" },
  { name: "Adductores en máquina", muscle: "Glúteos", type: "Aislamiento", equipment: "Máquina" },
  { name: "Abductores en máquina", muscle: "Glúteos", type: "Aislamiento", equipment: "Máquina" },
  { name: "Hiperextensión 45°", muscle: "Espalda", type: "Aislamiento", equipment: "Peso corporal" },
  { name: "Reverse hyperextension", muscle: "Glúteos", type: "Aislamiento", equipment: "Máquina" },
  { name: "Landmine row", muscle: "Espalda", type: "Compuesto", equipment: "Barra" },
  { name: "Landmine squat", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Jefferson curl", muscle: "Espalda", type: "Aislamiento", equipment: "Barra" },
  { name: "Zercher squat", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Anderson squat", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Pin squat", muscle: "Cuádriceps", type: "Compuesto", equipment: "Barra" },
  { name: "Spoto press", muscle: "Pecho", type: "Compuesto", equipment: "Barra" },
  { name: "Paused bench", muscle: "Pecho", type: "Compuesto", equipment: "Barra" },
  { name: "Close-grip bench", muscle: "Tríceps", type: "Compuesto", equipment: "Barra" },
  { name: "Wide-grip bench", muscle: "Pecho", type: "Compuesto", equipment: "Barra" },
  { name: "Deficit push-up", muscle: "Pecho", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Archer push-up", muscle: "Pecho", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Pike push-up", muscle: "Hombros", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Handstand push-up", muscle: "Hombros", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Muscle-up", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Front lever raise", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Chin-up lastrado", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
  { name: "Dominada lastrada", muscle: "Espalda", type: "Compuesto", equipment: "Peso corporal" },
];

export type CatalogExercise = {
  id: string;
  name: string;
  muscle: MuscleGroup;
  type: ExerciseType;
  equipment: string;
};

const seen = new Set<string>();

export const CATALOG: CatalogExercise[] = RAW.map((row) => {
  const id = row.id ?? `cat_${slugify(row.name)}`;
  return { id, name: row.name, muscle: row.muscle, type: row.type, equipment: row.equipment };
}).filter((row) => {
  if (seen.has(row.id)) return false;
  seen.add(row.id);
  return true;
});

export const KEY_EXERCISES = {
  bench: "bench_press",
  squat: "squat",
  deadlift: "deadlift",
  ohp: "ohp",
  pullup: "pullup",
  rdl: "rdl",
  hipThrust: "hip_thrust",
  latPulldown: "lat_pulldown",
  barbellRow: "barbell_row",
  inclineDb: "incline_db_press",
  lateralRaise: "lateral_raise",
  pushdown: "pushdown",
  ohExtension: "oh_extension",
  barbellCurl: "barbell_curl",
  hammerCurl: "hammer_curl",
  legPress: "leg_press",
  calf: "calf_raise",
  plank: "plank",
  facePull: "face_pull",
  dbBench: "db_bench",
} as const;

export const TEMPLATE_ROUTINES: {
  name: string;
  description: string;
  icon: string;
  color: string;
  exercises: { id: string; sets: number; reps: string; rest: number }[];
}[] = [
  {
    name: "Push",
    description: "Pecho, hombros y tríceps",
    icon: "flame",
    color: "#FF2D55",
    exercises: [
      { id: KEY_EXERCISES.bench, sets: 4, reps: "6-8", rest: 120 },
      { id: KEY_EXERCISES.inclineDb, sets: 3, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.ohp, sets: 3, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.lateralRaise, sets: 3, reps: "12-15", rest: 60 },
      { id: KEY_EXERCISES.pushdown, sets: 3, reps: "10-12", rest: 60 },
      { id: KEY_EXERCISES.ohExtension, sets: 3, reps: "10-12", rest: 60 },
    ],
  },
  {
    name: "Pull",
    description: "Espalda y bíceps",
    icon: "activity",
    color: "#007AFF",
    exercises: [
      { id: KEY_EXERCISES.deadlift, sets: 3, reps: "5", rest: 180 },
      { id: KEY_EXERCISES.pullup, sets: 4, reps: "6-10", rest: 120 },
      { id: KEY_EXERCISES.barbellRow, sets: 4, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.facePull, sets: 3, reps: "12-15", rest: 60 },
      { id: KEY_EXERCISES.barbellCurl, sets: 3, reps: "8-12", rest: 60 },
      { id: KEY_EXERCISES.hammerCurl, sets: 3, reps: "10-12", rest: 60 },
    ],
  },
  {
    name: "Legs",
    description: "Cuádriceps, femorales y glúteos",
    icon: "zap",
    color: "#34C759",
    exercises: [
      { id: KEY_EXERCISES.squat, sets: 4, reps: "5-8", rest: 180 },
      { id: KEY_EXERCISES.rdl, sets: 3, reps: "8-10", rest: 120 },
      { id: KEY_EXERCISES.legPress, sets: 3, reps: "10-12", rest: 90 },
      { id: KEY_EXERCISES.hipThrust, sets: 3, reps: "8-12", rest: 90 },
      { id: KEY_EXERCISES.calf, sets: 4, reps: "12-15", rest: 45 },
      { id: KEY_EXERCISES.plank, sets: 3, reps: "45s", rest: 45 },
    ],
  },
  {
    name: "Upper",
    description: "Tren superior completo",
    icon: "layers",
    color: "#FF9F0A",
    exercises: [
      { id: KEY_EXERCISES.bench, sets: 4, reps: "6-8", rest: 120 },
      { id: KEY_EXERCISES.barbellRow, sets: 4, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.ohp, sets: 3, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.latPulldown, sets: 3, reps: "8-12", rest: 90 },
      { id: KEY_EXERCISES.lateralRaise, sets: 3, reps: "12-15", rest: 60 },
      { id: KEY_EXERCISES.pushdown, sets: 3, reps: "10-12", rest: 60 },
      { id: KEY_EXERCISES.barbellCurl, sets: 3, reps: "8-12", rest: 60 },
    ],
  },
  {
    name: "Lower",
    description: "Tren inferior completo",
    icon: "target",
    color: "#5AC8FA",
    exercises: [
      { id: KEY_EXERCISES.squat, sets: 4, reps: "5-8", rest: 180 },
      { id: KEY_EXERCISES.rdl, sets: 3, reps: "8-10", rest: 120 },
      { id: KEY_EXERCISES.legPress, sets: 3, reps: "10-12", rest: 90 },
      { id: KEY_EXERCISES.hipThrust, sets: 3, reps: "8-12", rest: 90 },
      { id: KEY_EXERCISES.calf, sets: 4, reps: "12-15", rest: 45 },
      { id: KEY_EXERCISES.plank, sets: 3, reps: "45s", rest: 45 },
    ],
  },
  {
    name: "Full Body",
    description: "Cuerpo completo en una sesión",
    icon: "heart",
    color: "#AF52DE",
    exercises: [
      { id: KEY_EXERCISES.squat, sets: 3, reps: "6-8", rest: 120 },
      { id: KEY_EXERCISES.bench, sets: 3, reps: "6-8", rest: 120 },
      { id: KEY_EXERCISES.barbellRow, sets: 3, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.ohp, sets: 3, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.rdl, sets: 3, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.plank, sets: 3, reps: "45s", rest: 45 },
    ],
  },
  {
    name: "Torso",
    description: "Pecho, espalda y hombros",
    icon: "person",
    color: "#FF3B30",
    exercises: [
      { id: KEY_EXERCISES.bench, sets: 4, reps: "6-8", rest: 120 },
      { id: KEY_EXERCISES.barbellRow, sets: 4, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.ohp, sets: 3, reps: "8-10", rest: 90 },
      { id: KEY_EXERCISES.latPulldown, sets: 3, reps: "8-12", rest: 90 },
      { id: KEY_EXERCISES.inclineDb, sets: 3, reps: "8-12", rest: 75 },
      { id: KEY_EXERCISES.facePull, sets: 3, reps: "12-15", rest: 60 },
    ],
  },
  {
    name: "Pierna",
    description: "Cuádriceps, cadera y gemelos",
    icon: "zap",
    color: "#34C759",
    exercises: [
      { id: KEY_EXERCISES.squat, sets: 4, reps: "5-8", rest: 180 },
      { id: KEY_EXERCISES.rdl, sets: 3, reps: "8-10", rest: 120 },
      { id: KEY_EXERCISES.legPress, sets: 3, reps: "10-12", rest: 90 },
      { id: KEY_EXERCISES.hipThrust, sets: 3, reps: "8-12", rest: 90 },
      { id: KEY_EXERCISES.calf, sets: 4, reps: "12-15", rest: 45 },
    ],
  },
];
