/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TrainRouteImport } from './routes/train'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises/$exerciseId'
import { Route as HistoryWorkoutIdRouteImport } from './routes/history/$workoutId'
import { Route as RoutinesRoutineIdRouteImport } from './routes/routines/$routineId'
import { Route as ShareSlugRouteImport } from './routes/share/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => ExercisesRoute,
} as any)
const HistoryWorkoutIdRoute = HistoryWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => HistoryRoute,
} as any)
const RoutinesRoutineIdRoute = RoutinesRoutineIdRouteImport.update({
  id: '/$routineId',
  path: '/$routineId',
  getParentRoute: () => RoutinesRoute,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/feed'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/stats'
    | '/train'
    | '/exercises/$exerciseId'
    | '/history/$workoutId'
    | '/routines/$routineId'
    | '/share/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/feed'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/stats'
    | '/train'
    | '/exercises/$exerciseId'
    | '/history/$workoutId'
    | '/routines/$routineId'
    | '/share/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/feed'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/stats'
    | '/train'
    | '/exercises/$exerciseId'
    | '/history/$workoutId'
    | '/routines/$routineId'
    | '/share/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  FeedRoute: typeof FeedRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  ProgressRoute: typeof ProgressRoute
  RoutinesRoute: typeof RoutinesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TrainRoute: typeof TrainRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/history/$workoutId': {
      id: '/history/$workoutId'
      path: '/$workoutId'
      fullPath: '/history/$workoutId'
      preLoaderRoute: typeof HistoryWorkoutIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/routines/$routineId': {
      id: '/routines/$routineId'
      path: '/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof RoutinesRoutineIdRouteImport
      parentRoute: typeof RoutinesRoute
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

interface HistoryRouteChildren {
  HistoryWorkoutIdRoute: typeof HistoryWorkoutIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryWorkoutIdRoute: HistoryWorkoutIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface RoutinesRouteChildren {
  RoutinesRoutineIdRoute: typeof RoutinesRoutineIdRoute
}

const RoutinesRouteChildren: RoutinesRouteChildren = {
  RoutinesRoutineIdRoute: RoutinesRoutineIdRoute,
}

const RoutinesRouteWithChildren = RoutinesRoute._addFileChildren(
  RoutinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  FeedRoute: FeedRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  ProgressRoute: ProgressRoute,
  RoutinesRoute: RoutinesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TrainRoute: TrainRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
