/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiAuthHealthRouteImport } from './routes/api/auth-health'
import { Route as CompareUsernameRouteImport } from './routes/compare/$username'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises/$exerciseId'
import { Route as FeedRequestsRouteImport } from './routes/feed/requests'
import { Route as FeedSearchRouteImport } from './routes/feed/search'
import { Route as HistoryWorkoutIdRouteImport } from './routes/history/$workoutId'
import { Route as RoutinesRoutineIdRouteImport } from './routes/routines/$routineId'
import { Route as ShareSlugRouteImport } from './routes/share/$slug'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthHealthRoute = ApiAuthHealthRouteImport.update({
  id: '/api/auth-health',
  path: '/api/auth-health',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareUsernameRoute = CompareUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => CompareRoute,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => ExercisesRoute,
} as any)
const FeedRequestsRoute = FeedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => FeedRoute,
} as any)
const FeedSearchRoute = FeedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => FeedRoute,
} as any)
const HistoryWorkoutIdRoute = HistoryWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => HistoryRoute,
} as any)
const RoutinesRoutineIdRoute = RoutinesRoutineIdRouteImport.update({
  id: '/$routineId',
  path: '/$routineId',
  getParentRoute: () => RoutinesRoute,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRouteWithChildren
  '/exercises': typeof ExercisesRouteWithChildren
  '/feed': typeof FeedRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/api/auth-health': typeof ApiAuthHealthRoute
  '/compare/$username': typeof CompareUsernameRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/feed/requests': typeof FeedRequestsRoute
  '/feed/search': typeof FeedSearchRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRouteWithChildren
  '/exercises': typeof ExercisesRouteWithChildren
  '/feed': typeof FeedRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/api/auth-health': typeof ApiAuthHealthRoute
  '/compare/$username': typeof CompareUsernameRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/feed/requests': typeof FeedRequestsRoute
  '/feed/search': typeof FeedSearchRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRouteWithChildren
  '/exercises': typeof ExercisesRouteWithChildren
  '/feed': typeof FeedRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/train': typeof TrainRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/api/auth-health': typeof ApiAuthHealthRoute
  '/compare/$username': typeof CompareUsernameRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/feed/requests': typeof FeedRequestsRoute
  '/feed/search': typeof FeedSearchRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/exercises'
    | '/feed'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/train'
    | '/tutorial'
    | '/welcome'
    | '/api/auth-health'
    | '/compare/$username'
    | '/exercises/$exerciseId'
    | '/feed/requests'
    | '/feed/search'
    | '/history/$workoutId'
    | '/routines/$routineId'
    | '/share/$slug'
    | '/u/$username'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/exercises'
    | '/feed'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/train'
    | '/tutorial'
    | '/welcome'
    | '/api/auth-health'
    | '/compare/$username'
    | '/exercises/$exerciseId'
    | '/feed/requests'
    | '/feed/search'
    | '/history/$workoutId'
    | '/routines/$routineId'
    | '/share/$slug'
    | '/u/$username'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/exercises'
    | '/feed'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/train'
    | '/tutorial'
    | '/welcome'
    | '/api/auth-health'
    | '/compare/$username'
    | '/exercises/$exerciseId'
    | '/feed/requests'
    | '/feed/search'
    | '/history/$workoutId'
    | '/routines/$routineId'
    | '/share/$slug'
    | '/u/$username'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRouteWithChildren
  ExercisesRoute: typeof ExercisesRouteWithChildren
  FeedRoute: typeof FeedRouteWithChildren
  HistoryRoute: typeof HistoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  ProgressRoute: typeof ProgressRoute
  RoutinesRoute: typeof RoutinesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  StatsRoute: typeof StatsRoute
  TrainRoute: typeof TrainRoute
  TutorialRoute: typeof TutorialRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAuthHealthRoute: typeof ApiAuthHealthRoute
  ShareSlugRoute: typeof ShareSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-health': {
      id: '/api/auth-health'
      path: '/api/auth-health'
      fullPath: '/api/auth-health'
      preLoaderRoute: typeof ApiAuthHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$username': {
      id: '/compare/$username'
      path: '/$username'
      fullPath: '/compare/$username'
      preLoaderRoute: typeof CompareUsernameRouteImport
      parentRoute: typeof CompareRoute
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/feed/requests': {
      id: '/feed/requests'
      path: '/requests'
      fullPath: '/feed/requests'
      preLoaderRoute: typeof FeedRequestsRouteImport
      parentRoute: typeof FeedRoute
    }
    '/feed/search': {
      id: '/feed/search'
      path: '/search'
      fullPath: '/feed/search'
      preLoaderRoute: typeof FeedSearchRouteImport
      parentRoute: typeof FeedRoute
    }
    '/history/$workoutId': {
      id: '/history/$workoutId'
      path: '/$workoutId'
      fullPath: '/history/$workoutId'
      preLoaderRoute: typeof HistoryWorkoutIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/routines/$routineId': {
      id: '/routines/$routineId'
      path: '/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof RoutinesRoutineIdRouteImport
      parentRoute: typeof RoutinesRoute
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompareRouteChildren {
  CompareUsernameRoute: typeof CompareUsernameRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareUsernameRoute: CompareUsernameRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface ExercisesRouteChildren {
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

interface FeedRouteChildren {
  FeedRequestsRoute: typeof FeedRequestsRoute
  FeedSearchRoute: typeof FeedSearchRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedRequestsRoute: FeedRequestsRoute,
  FeedSearchRoute: FeedSearchRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

interface HistoryRouteChildren {
  HistoryWorkoutIdRoute: typeof HistoryWorkoutIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryWorkoutIdRoute: HistoryWorkoutIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface RoutinesRouteChildren {
  RoutinesRoutineIdRoute: typeof RoutinesRoutineIdRoute
}

const RoutinesRouteChildren: RoutinesRouteChildren = {
  RoutinesRoutineIdRoute: RoutinesRoutineIdRoute,
}

const RoutinesRouteWithChildren = RoutinesRoute._addFileChildren(
  RoutinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRouteWithChildren,
  ExercisesRoute: ExercisesRouteWithChildren,
  FeedRoute: FeedRouteWithChildren,
  HistoryRoute: HistoryRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  ProgressRoute: ProgressRoute,
  RoutinesRoute: RoutinesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  StatsRoute: StatsRoute,
  TrainRoute: TrainRoute,
  TutorialRoute: TutorialRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAuthHealthRoute: ApiAuthHealthRoute,
  ShareSlugRoute: ShareSlugRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
